config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :employees
  get 'home',to: 'welcome#home'
  get 'about', to: 'welcome#about'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates:Firstname,presence:true,length:{minimum:5,maximum:30}
#validates :firstname, presence :true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
   def index
     @employee=Employee.all
   end

  def new
    @employee=Employee.new
  end

  def edit
    @employee=Employee.find(params[:id])
  end

  def update
    @employee=Employee.find(params[:id])
    if @employee.update(employeeparam)
      flash[:notice]="Employee Updated Sucessfully"
      redirect_to @employee
    else
      render 'edit'
    end
  end

  def create
      @employee=Employee.new(employeeparam)
      if @employee.save
        flash[:notice]="Employee Added Sucessfully"
          redirect_to @employee
      else
         render 'new'
      end
  end

  def show
    @employee=Employee.find(params[:id])
  end
 def destroy
    @employee=Employee.find(params[:id])
    @employee.destroy
    flash[:notice]="Employee Deleted Sucessfully"
    redirect_to employees_path
 end
  private
    def employeeparam
        params.require(:employee).permit(:Firstname,:Lastname,:gender)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:Username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end
  def index
  end

  def about
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_form.html.erb
<% if @employee.errors.any?  %>
  <ul>
  <%= @employee.errors.full_messages.each do |msg| %>
    <li> <%= msg %></li>
  <%  end %>
</ul>
<% end %>

<%= form_for @employee do |f| %>
 <%= f.label:Firstname  %>
<%=  f.text_field:Firstname %>
<br>
<%= f.label:Lastname %>
<%= f.text_field:Lastname %>
<br>
<br>
<%= f.radio_button(:gender,'Male') %>Male &nbsp; <%= f.radio_button(:gender,'Female') %>Female
<br>
<%= f.submit %>
<% end %>

app/views/employees/edit.html.erb
<h2>Edit employee </h2>
<%= render 'form' %>

app/views/employees/index.html.erb
<h4>List of Employee</h4>
<%=link_to 'Create New Employee',new_employee_path %>
<table>
  <tr>
<th>First Name</th>
<th>Last Name</th>
<th>Gender</th>
<th>Edit</th>
<th>Delete</th>
</tr>
<% @employee.each do |employee| %>
<tr>
    <td><%= employee.Firstname %></td>
  <td><%= employee.Lastname %></td>
    <td><%= employee.gender %></td>
    <td><%=link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%=link_to 'Delete',employee_path(employee),method: :delete,data:{confirm:"Are you sure?"} %></td>
  </tr>
<% end %>
</table>

app/views/employees/new.html.erb
<h1>Create an Employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<h1>Employee Info</h1>

Firstname:<%= @employee.Firstname %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Avision</title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<body>
  <% flash.each do |name,msg| %>
  <ul><li><%= msg %></li>
  </ul>
  <% end %>
<%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Username %>
    <%= form.text_field :Username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.Username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.Username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<h2> About us Page</h2>

<%= link_to 'Home', home_path  %>

<%= link_to 'Index', root_path  %>

app/views/welcome/home.html.erb
<h1>This is home page</h1>
<%= link_to 'About', about_path %>

<%= link_to 'Index', root_path %>